name: Build/release

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Setup Python
        uses: actions/setup-python@v5.1.0
      - name: install requirements
        run: pip install pyinstaller
      - name: build
        run: pyinstaller --onefile myscript.py
          
